'use client'

export default function Home () {
    return (
        <section>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
            <p>hallo</p>
        </section>
    )
}